### ISSUE TITLE
Add architecture for simulators

### ISSUE THREAD

**Issue by tooszovski** [shuftipro/iOS-SDK#8]
Please add x86_64-apple-ios-simulator architecture for simulator supporting

**Comment by sharjeelahmed** [comment]
yeah i am facing the same issue

**Comment by shuftipro** [comment]
It's recommended from our side to test the SDK on a physical device as certain processes and AI models running in the background ensure active liveness by performing different authenticity checks. In addition, our auto-capturing is fully functional on physical devices as the system captures real-time frames to calculate the results. Hence, it won't be feasible to support the x86_64-apple-ios-simulator architecture in the simulator as Simulators do not have the physical camera to capture the live images.

**Comment by sharjeelahmed** [comment]
Thank you for your response. I understand that the SDK is designed to work with a physical device's camera and that it's not currently possible to run the SDK in the simulator. Because of this, I cannot run my project in the simulator. I was wondering if there are any possible workarounds or alternatives for testing the SDK on a simulator? Also, do you have any plans to support the x86_64-apple-ios-simulator architecture in the future, or if there's any other way to test the SDK on a simulator?
It would be greatly appreciated if you could provide any solution for this as it's preventing me from testing my project on the simulator. Also please let me know if you need more information about my use-case
<img width="733" alt="Screenshot 2023-01-13 at 7 23 07 PM" src="https://user-images.githubusercontent.com/7043500/212342757-561384a8-ee80-46e6-8a27-d308aab34681.png">

**Comment by kelvindezy** [comment]
> Thank you for your response. I understand that the SDK is designed to work with a physical device's camera and that it's not currently possible to run the SDK in the simulator. Because of this, I cannot run my project in the simulator. I was wondering if there are any possible workarounds or alternatives for testing the SDK on a simulator? Also, do you have any plans to support the x86_64-apple-ios-simulator architecture in the future, or if there's any other way to test the SDK on a simulator? It would be greatly appreciated if you could provide any solution for this as it's preventing me from testing my project on the simulator. Also please let me know if you need more information about my use-case <img alt="Screenshot 2023-01-13 at 7 23 07 PM" width="733" src="https://user-images.githubusercontent.com/7043500/212342757-561384a8-ee80-46e6-8a27-d308aab34681.png">

I agree with this. because after adding this library, I wont be able to build the application on simulator for this. a usual workaround is to try catch error when calling it while using simulator.

**Comment by charles85** [comment]
I am agreed with Kelvin. As we need constantly to improve and adding features to our app, it will be very annoying by having to uninstall the library and continue working with our other requirements and installing it back again for deployment later.
